### ISSUE TITLE
Improve Symbology 

### ISSUE THREAD

**Issue by dexterslu** [CityOfDetroit/zoom-nineteen#2]
We should think through the way we display data on the map (symbols vs circles) and consider styling based on user zoom level.

**Symbols**
<img width="177" alt="screen shot 2017-04-12 at 1 57 49 pm" src="https://cloud.githubusercontent.com/assets/3484455/24972318/09898d8a-1f89-11e7-9f9d-2258bac41dd2.png">

**Circles**
<img width="224" alt="screen shot 2017-04-12 at 1 58 15 pm" src="https://cloud.githubusercontent.com/assets/3484455/24972312/059ad332-1f89-11e7-8ced-8b542d6fd8a8.png">

**Comment by jmcbroom** [comment]
I agree. We're using icons because it's the easiest way to do the dataset for-loop.

Circles have the advantage of using the zoom-level stop functions, but if you're displaying >1 dataset things get tricky. I like the icons because you don't have to remember what colors mean what. although whether icons are much better in this regard is up for discussion

We could also set up a zoom listener to `map.setPaintProperty(somelayer, "icon-image", "whatever-15)` when the zoom level goes above a certain number.

**Comment by jmcbroom** [comment]
Mapbox GL has cool `icon-size` layout and `icon-opacity` symbol properties that help out here!
